server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  - job_name: journal
    journal:
      max_age: 12h
      path: /var/log/journal
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels:
          - __journal__systemd_unit
        target_label: unit
      - source_labels:
          - __journal__hostname
        target_label: host

  - job_name: syslog
    syslog:
      listen_address: 0.0.0.0:1514
      idle_timeout: 60s
      label_structured_data: true
      labels:
        job: syslog
    relabel_configs:
      - source_labels:
          - __syslog_message_hostname
        target_label: host
      - source_labels:
          - __syslog_message_facility
        target_label: facility
      - source_labels:
          - __syslog_message_severity
        target_label: level
