apiVersion: 1
contactPoints:
  - orgId: 1
    name: email
    receivers:
      - uid: email-receiver
        type: email
        settings:
          addresses: romabilibov@gmail.com
        disableResolveMessage: false
